[project]
name = "balance-pyexcel-pipeline"
version = "0.1.0"
description = "Python ETL pipeline for the BALANCE-pyexcel shared finance tracker."
authors = [
    {name = "Ryan Zimmerman",email = "your-email@example.com"}
]
readme = "README.md"
requires-python = "^3.11"
dependencies = [
    "pandas (>=2.2.3,<3.0.0)",
    "python-dotenv (>=1.1.0,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pytest-cov = "^6.1.1"
black = "^25.1.0"
ruff = "^0.11.6"

